# Generated by Django 2.2.6 on 2019-10-24 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='user_likes',
            field=models.ManyToManyField(related_name='like_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
